FROM    debian:bookworm

RUN     apt update -y
RUN     apt-get install -y mariadb-server mariadb-client

COPY    conf/50-server.cnf /etc/mysql/mariadb.conf.d/50-server.cnf

RUN     mkdir -p /var/run/mysqld
# RUN     mkdir -p /var/lib/mysql
RUN     chown -R mysql:mysql /var/run/mysqld/
RUN     chmod 777 /var/run/mysqld/
# RUN     chown mysql:mysql /var/lib/mysql/
# RUN     chmod -R 755 /var/lib/mysql/

EXPOSE  3306

COPY    ./conf/50-server.cnf /etc/mysql/my.cnf
COPY    ./conf/init.sh /usr/local/bin/init.sh
RUN     chmod +x /usr/local/bin/init.sh

CMD ["/bin/bash", "/usr/local/bin/init.sh"]
