FROM debian:buster

RUN apt update
RUN apt-get install -y wget unzip php7.3 php-fpm php-mysql mariadb-client
COPY ./conf/www.conf /etc/php/7.3/fpm/pool.d/www.conf
RUN chmod 777 /etc/php/7.3/fpm/pool.d/www.conf

RUN wget https://fr.wordpress.org/wordpress-6.8-fr_FR.tar.gz -P /var/www
RUN cd /var/www && tar -xvf wordpress-6.8-fr_FR.tar.gz && rm wordpress-6.8-fr_FR.tar.gz
RUN chown -R www-data:www-data /var/www/wordpress/
RUN chmod -R 755 /var/www/wordpress/*


RUN wget https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar \
	&& chmod +x wp-cli.phar \
	&& mv wp-cli.phar /usr/local/bin/wp



EXPOSE 9000

COPY ./conf/wpscript.sh /usr/local/bin/wpscript.sh
RUN chmod +x /usr/local/bin/wpscript.sh

WORKDIR /var/www/wordpress

CMD ["/bin/bash", "/usr/local/bin/wpscript.sh"]
